safe: true
source: /

remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
description: A checklist of less obvious things for conference organisers that help build amazing, wonderful, welcoming and inclusive events.
